name = "finperm"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Finperm"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "batteries"
scope = "leanprover-community"

[[lean_lib]]
name = "Finperm"
